export interface Recipe {
  id: string;
  name: string;
  duration: number; // minutes
  difficulty: "쉬움" | "중간" | "어려움";
  servings: string;
  ingredients: { name: string; amount: string }[];
  steps: string[];
  image: string;
  matchIngredients: string[];
  tag?: string;
}

export const RECIPES: Recipe[] = [
  // ──────────────────────────────────────────
  // 한식 20개
  // ──────────────────────────────────────────
  {
    id: "kimchi-stew",
    name: "김치찌개",
    duration: 25,
    difficulty: "중간",
    servings: "2인분",
    tag: "🍲 집밥 정석",
    ingredients: [
      { name: "묵은지", amount: "200g" },
      { name: "돼지고기 삼겹살", amount: "150g" },
      { name: "두부", amount: "1/2모 (200g)" },
      { name: "대파", amount: "1/2대" },
      { name: "다진마늘", amount: "1작은술" },
      { name: "고춧가루", amount: "1큰술" },
      { name: "국간장", amount: "1큰술" },
      { name: "참기름", amount: "1작은술" },
      { name: "물", amount: "350ml (종이컵 약 1.5컵)" },
    ],
    steps: [
      "김치는 2cm 크기로 썰고, 삼겹살도 같은 크기로 썰어 준비합니다.",
      "두부는 1.5cm 두께로 썰고, 대파는 어슷하게 썹니다.",
      "냄비에 참기름을 두르고 삼겹살과 김치를 중불에서 3분간 볶아 기름을 냅니다.",
      "물 350ml를 붓고 강불에서 끓입니다. 끓어오르면 거품을 걷어냅니다.",
      "다진마늘, 고춧가루, 국간장을 넣고 중불에서 5분간 끓입니다.",
      "두부와 대파를 넣고 3분간 더 끓입니다. 간이 부족하면 소금으로 조절합니다.",
    ],
    image: "/images/kimchi_stew.png",
    matchIngredients: ["김치", "돼지고기", "두부", "대파", "마늘"],
  },
  {
    id: "doenjang-stew",
    name: "된장찌개",
    duration: 20,
    difficulty: "중간",
    servings: "2인분",
    tag: "🌿 구수한 맛",
    ingredients: [
      { name: "된장", amount: "2큰술" },
      { name: "두부", amount: "1/2모 (200g)" },
      { name: "애호박", amount: "1/3개" },
      { name: "감자", amount: "1/2개" },
      { name: "대파", amount: "1/2대" },
      { name: "다진마늘", amount: "1작은술" },
      { name: "멸치 다시마 육수", amount: "500ml (종이컵 약 2.5컵)" },
    ],
    steps: [
      "감자는 1.5cm 깍둑썰기, 애호박은 반달모양, 두부는 2cm 사각형, 대파는 어슷 썹니다.",
      "냄비에 육수 500ml를 붓고 끓으면 감자를 먼저 넣어 3분 끓입니다.",
      "된장을 체에 눌러 고르게 풀어 넣고 다진마늘을 추가합니다.",
      "애호박을 넣고 3분, 두부를 넣고 2분, 마지막에 대파를 넣고 1분 더 끓입니다.",
      "간이 부족하면 소금이나 국간장으로 조절합니다.",
    ],
    image: "/images/doenjang_stew.png",
    matchIngredients: ["된장", "두부", "애호박", "감자", "대파"],
  },
  {
    id: "jeyuk-bokkeum",
    name: "제육볶음",
    duration: 20,
    difficulty: "중간",
    servings: "2인분",
    tag: "🌶️ 매콤 쫄깃",
    ingredients: [
      { name: "돼지고기 앞다리살", amount: "300g" },
      { name: "양파", amount: "1/2개" },
      { name: "대파", amount: "1/2대" },
      { name: "고추장", amount: "2큰술" },
      { name: "간장", amount: "1큰술" },
      { name: "설탕", amount: "1큰술" },
      { name: "다진마늘", amount: "1큰술" },
      { name: "참기름", amount: "1작은술" },
      { name: "식용유", amount: "1큰술" },
    ],
    steps: [
      "돼지고기를 0.5cm 두께로 얇게 썹니다.",
      "고추장, 간장, 설탕, 다진마늘, 참기름을 섞어 양념장을 만듭니다.",
      "고기에 양념장을 버무려 10분 이상 재웁니다.",
      "양파는 채 썰고, 대파는 어슷 썹니다.",
      "달군 팬에 식용유를 두르고 강불에서 양념 고기를 2~3분 볶습니다.",
      "양파와 대파를 넣고 1~2분 더 볶아 불향을 냅니다.",
    ],
    image: "/images/stir_fried_pork.png",
    matchIngredients: ["돼지고기", "양파", "고추장", "간장", "마늘"],
  },
  {
    id: "kimchi-fried-rice",
    name: "김치볶음밥",
    duration: 15,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🔥 인기 만점",
    ingredients: [
      { name: "신김치", amount: "150g" },
      { name: "밥", amount: "300g (공기 1개)" },
      { name: "대파", amount: "1/4대" },
      { name: "계란", amount: "1개" },
      { name: "간장", amount: "1큰술" },
      { name: "참기름", amount: "1작은술" },
      { name: "식용유", amount: "1큰술" },
    ],
    steps: [
      "김치는 2cm 크기로 썰고, 대파는 송송 썹니다.",
      "달군 팬에 식용유를 두르고 대파와 김치를 2~3분 볶습니다.",
      "팬 가장자리에 간장을 두르고 살짝 태워 불향을 냅니다.",
      "밥을 넣고 주걱으로 누르며 강불에서 2분간 볶습니다.",
      "참기름을 두르고 마무리합니다. 반숙 계란 프라이를 올려 냅니다.",
    ],
    image: "/images/kimchi_fried_rice.png",
    matchIngredients: ["김치", "밥", "계란", "대파", "간장"],
  },
  {
    id: "bibimbap",
    name: "비빔밥",
    duration: 30,
    difficulty: "중간",
    servings: "1인분",
    tag: "🌈 영양 만점",
    ingredients: [
      { name: "밥", amount: "300g (공기 1개)" },
      { name: "시금치", amount: "80g" },
      { name: "당근", amount: "1/4개" },
      { name: "콩나물", amount: "80g" },
      { name: "계란", amount: "1개" },
      { name: "고추장", amount: "1.5큰술" },
      { name: "참기름", amount: "1큰술" },
      { name: "간장", amount: "1작은술" },
    ],
    steps: [
      "시금치는 끓는 물에 30초 데쳐 찬물에 헹군 뒤 참기름, 소금으로 무칩니다.",
      "콩나물은 끓는 물 300ml에 뚜껑을 덮고 5분 삶아 식혀 간장, 참기름으로 무칩니다.",
      "당근은 채 썰어 소금 한 꼬집으로 볶아둡니다.",
      "달군 팬에 계란 프라이(반숙)를 만듭니다.",
      "따뜻한 밥 위에 각 나물을 색상 맞춰 올리고 계란 프라이를 올립니다.",
      "고추장과 참기름을 곁들여 취향대로 비벼 먹습니다.",
    ],
    image: "/images/jeyuk_deopbap.png",
    matchIngredients: ["밥", "시금치", "당근", "콩나물", "계란", "고추장"],
  },
  {
    id: "sundubu-jjigae",
    name: "순두부찌개",
    duration: 20,
    difficulty: "쉬움",
    servings: "1~2인분",
    tag: "🔴 매콤 부드러움",
    ingredients: [
      { name: "순두부", amount: "1팩 (350g)" },
      { name: "다진돼지고기", amount: "80g" },
      { name: "대파", amount: "1/3대" },
      { name: "고춧가루", amount: "1.5큰술" },
      { name: "다진마늘", amount: "1작은술" },
      { name: "국간장", amount: "1큰술" },
      { name: "계란", amount: "1개" },
      { name: "물", amount: "300ml (종이컵 약 1.5컵)" },
    ],
    steps: [
      "달군 냄비에 참기름을 두르고 다진돼지고기와 고춧가루를 넣어 1분간 볶아 붉은 기름을 냅니다.",
      "물 300ml를 붓고 강불에서 한소끔 끓입니다.",
      "국간장과 다진마늘을 넣고 중불에서 3분 끓입니다.",
      "순두부를 큰 숟가락으로 떠서 넣고 2~3분 더 끓입니다.",
      "마지막에 계란 한 개를 깨뜨려 넣고 대파를 올린 뒤 반숙으로 마무리합니다.",
    ],
    image: "/images/kimchi_stew.png",
    matchIngredients: ["순두부", "돼지고기", "대파", "고춧가루", "계란"],
  },
  {
    id: "samgyeopsal",
    name: "삼겹살 구이",
    duration: 20,
    difficulty: "쉬움",
    servings: "2인분",
    tag: "🥓 고소 담백",
    ingredients: [
      { name: "삼겹살", amount: "300g" },
      { name: "상추", amount: "한 줌" },
      { name: "깻잎", amount: "10장" },
      { name: "다진마늘", amount: "1큰술" },
      { name: "된장", amount: "1큰술" },
      { name: "쌈장", amount: "2큰술" },
    ],
    steps: [
      "삼겹살은 1cm 두께로 적당히 썰어 둡니다.",
      "그릴 팬 또는 일반 팬을 강불로 달굽니다. 기름 없이 삼겹살을 올립니다.",
      "앞뒤로 각각 3~4분씩 노릇하게 굽습니다. 기름이 많이 나오면 키친타월로 닦아냅니다.",
      "구운 고기를 가위로 먹기 좋게 잘라 상추와 깻잎으로 싸서 쌈장과 함께 냅니다.",
      "함께 먹는 다진마늘은 팬에 살짝 구우면 더 맛있습니다.",
    ],
    image: "/images/stir_fried_pork.png",
    matchIngredients: ["삼겹살", "상추", "깻잎", "마늘", "된장"],
  },
  {
    id: "budae-jjigae",
    name: "부대찌개",
    duration: 20,
    difficulty: "중간",
    servings: "2인분",
    tag: "🥘 푸짐 얼큰",
    ingredients: [
      { name: "스팸", amount: "1/2캔 (약 160g)" },
      { name: "비엔나소시지", amount: "100g" },
      { name: "김치", amount: "100g" },
      { name: "두부", amount: "1/4모" },
      { name: "라면", amount: "1/2개 (선택)" },
      { name: "치즈", amount: "1장" },
      { name: "고춧가루", amount: "1큰술" },
      { name: "다진마늘", amount: "1작은술" },
      { name: "물", amount: "500ml (종이컵 약 2.5컵)" },
    ],
    steps: [
      "스팸, 소시지, 김치, 두부를 먹기 좋은 크기로 썰어 냄비에 가지런히 담습니다.",
      "물 500ml를 붓고 고춧가루, 다진마늘을 올립니다.",
      "뚜껑을 덮고 강불로 끓입니다. 끓으면 중불로 줄여 5분 더 끓입니다.",
      "라면을 넣으면 3~4분 후 익습니다.",
      "치즈를 올려 녹으면 완성합니다.",
    ],
    image: "/images/kimchi_stew.png",
    matchIngredients: ["스팸", "소시지", "김치", "두부", "치즈"],
  },
  {
    id: "japchae",
    name: "잡채",
    duration: 30,
    difficulty: "중간",
    servings: "2인분",
    tag: "🍜 명절 단골",
    ingredients: [
      { name: "당면", amount: "100g" },
      { name: "쇠고기 (우둔살)", amount: "100g" },
      { name: "시금치", amount: "80g" },
      { name: "당근", amount: "1/3개" },
      { name: "양파", amount: "1/2개" },
      { name: "간장", amount: "3큰술" },
      { name: "설탕", amount: "1큰술" },
      { name: "참기름", amount: "1큰술" },
      { name: "물", amount: "1L (면 삶기용)" },
    ],
    steps: [
      "냄비에 물 1L를 끓여 당면을 8분간 삶고 찬물에 헹궈 식힙니다.",
      "소고기는 채 썰어 간장 1큰술, 설탕 1/2큰술로 밑간합니다.",
      "각 채소를 따로따로 소금 약간으로 볶아 익혀 식혀 둡니다.",
      "밑간한 소고기를 팬에 볶아 익힙니다.",
      "삶은 당면에 간장 2큰술, 설탕 1/2큰술, 참기름을 넣고 볶아가며 양념합니다.",
      "모든 재료를 합치고 참기름 1큰술로 마무리합니다.",
    ],
    image: "/images/jeyuk_deopbap.png",
    matchIngredients: ["당면", "소고기", "시금치", "당근", "양파", "간장"],
  },
  {
    id: "bulgogi",
    name: "불고기",
    duration: 25,
    difficulty: "중간",
    servings: "2인분",
    tag: "🥩 달콤 고소",
    ingredients: [
      { name: "소고기 (불고기용)", amount: "300g" },
      { name: "양파", amount: "1/2개" },
      { name: "대파", amount: "1/3대" },
      { name: "간장", amount: "3큰술" },
      { name: "설탕", amount: "1큰술" },
      { name: "배즙", amount: "3큰술" },
      { name: "다진마늘", amount: "1큰술" },
      { name: "참기름", amount: "1큰술" },
    ],
    steps: [
      "소고기는 키친타월로 핏물을 제거합니다.",
      "간장, 설탕, 배즙, 다진마늘, 참기름을 섞어 양념장을 만듭니다.",
      "고기에 양념장을 버무려 냉장고에서 30분~1시간 재웁니다.",
      "양파는 채 썰고, 대파는 어슷 썹니다.",
      "달군 팬에 양념 고기와 양파를 함께 넣어 강불에서 3~4분 볶습니다.",
      "고기가 익으면 대파를 넣어 1분 더 볶아 완성합니다.",
    ],
    image: "/images/jeyuk_deopbap.png",
    matchIngredients: ["소고기", "양파", "대파", "간장", "배즙", "마늘"],
  },
  {
    id: "galbi-jjim",
    name: "갈비찜",
    duration: 90,
    difficulty: "어려움",
    servings: "3~4인분",
    tag: "🍖 특별한 날",
    ingredients: [
      { name: "소갈비", amount: "600g" },
      { name: "무", amount: "200g" },
      { name: "당근", amount: "1개" },
      { name: "간장", amount: "4큰술" },
      { name: "설탕", amount: "2큰술" },
      { name: "다진마늘", amount: "1큰술" },
      { name: "배즙", amount: "4큰술" },
      { name: "물", amount: "500ml (종이컵 약 2.5컵)" },
    ],
    steps: [
      "갈비는 찬물에 1시간 담가 핏물을 빼고 끓는 물에 5분 데쳐 씻습니다.",
      "무와 당근은 4cm 크기로 썰어 모서리를 다듬습니다.",
      "냄비에 물 500ml와 간장, 설탕, 배즙, 마늘을 섞어 양념을 만듭니다.",
      "갈비와 무를 넣고 강불로 끓입니다. 끓으면 중불로 줄여 30분 더 끓입니다.",
      "당근을 넣고 20분 더 조려 양념이 배면 완성합니다.",
    ],
    image: "/images/stir_fried_pork.png",
    matchIngredients: ["소갈비", "무", "당근", "간장", "마늘"],
  },
  {
    id: "gyeran-mari",
    name: "계란말이",
    duration: 10,
    difficulty: "쉬움",
    servings: "1~2인분",
    tag: "🥚 초간단",
    ingredients: [
      { name: "계란", amount: "4개" },
      { name: "대파", amount: "1/4대" },
      { name: "당근", amount: "1/6개" },
      { name: "소금", amount: "1/4작은술" },
      { name: "물", amount: "2큰술 (30ml)" },
      { name: "식용유", amount: "2큰술" },
    ],
    steps: [
      "당근과 대파를 잘게 다져 준비합니다.",
      "계란 4개에 물 30ml, 소금을 넣고 잘 풀어 당근, 대파를 섞습니다.",
      "기름을 두른 팬을 약불로 달구고, 계란물의 절반을 부어 반 정도 굳으면 말아줍니다.",
      "남은 계란물을 부어 반복해 원통 모양으로 만듭니다.",
      "약불에서 앞뒤로 1~2분 더 익힌 뒤 1.5cm로 썰어 냅니다.",
    ],
    image: "/images/egg_roll.png",
    matchIngredients: ["계란", "대파", "당근"],
  },
  {
    id: "gyeran-bap",
    name: "간장 계란밥",
    duration: 5,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "⚡ 3분 완성",
    ingredients: [
      { name: "계란", amount: "1개" },
      { name: "밥", amount: "300g (공기 1개)" },
      { name: "버터", amount: "7g" },
      { name: "간장", amount: "1큰술" },
      { name: "참기름", amount: "1작은술" },
      { name: "통깨", amount: "약간" },
    ],
    steps: [
      "따뜻한 밥 위에 버터를 올려 녹입니다.",
      "계란을 깨뜨려 올리고 간장과 참기름을 둘러줍니다.",
      "숟가락으로 계란 노른자와 함께 비벼 줍니다.",
      "통깨를 뿌려 완성합니다.",
    ],
    image: "/images/egg_roll.png",
    matchIngredients: ["계란", "밥", "버터", "간장"],
  },
  {
    id: "chamchi-mayo-rice",
    name: "참치마요 덮밥",
    duration: 8,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🐟 고소 담백",
    ingredients: [
      { name: "참치캔", amount: "1캔 (150g)" },
      { name: "마요네즈", amount: "2큰술" },
      { name: "밥", amount: "300g" },
      { name: "쪽파", amount: "약간" },
      { name: "간장", amount: "1작은술" },
      { name: "참기름", amount: "1작은술" },
    ],
    steps: [
      "참치캔을 열어 기름을 꾹 짜서 제거합니다.",
      "참치에 마요네즈, 간장, 참기름을 넣고 잘 섞습니다.",
      "따뜻한 밥 위에 참치마요를 올립니다.",
      "쪽파를 송송 썰어 올려 완성합니다.",
    ],
    image: "/images/kimchi_fried_rice.png",
    matchIngredients: ["참치캔", "마요네즈", "밥", "쪽파"],
  },
  {
    id: "gamja-jorim",
    name: "감자조림",
    duration: 25,
    difficulty: "쉬움",
    servings: "2인분",
    tag: "🥔 단짠 반찬",
    ingredients: [
      { name: "감자", amount: "2개 (약 300g)" },
      { name: "간장", amount: "2큰술" },
      { name: "설탕", amount: "1큰술" },
      { name: "올리고당", amount: "1큰술" },
      { name: "다진마늘", amount: "1작은술" },
      { name: "물", amount: "150ml (종이컵 약 0.7컵)" },
      { name: "참기름", amount: "1작은술" },
    ],
    steps: [
      "감자는 껍질을 벗겨 한 입 크기로 깍둑 썰고 찬물에 10분 담가 전분을 뺍니다.",
      "냄비에 물 150ml, 간장, 설탕, 올리고당, 마늘을 넣고 섞습니다.",
      "감자를 넣고 뚜껑을 덮어 중불에서 10분간 끓입니다.",
      "뚜껑을 열고 강불에서 국물이 졸아들 때까지 저어가며 조립니다.",
      "참기름을 두르고 통깨를 뿌려 완성합니다.",
    ],
    image: "/images/stir_fried_pork.png",
    matchIngredients: ["감자", "간장", "설탕", "마늘"],
  },
  {
    id: "haemul-pajeon",
    name: "해물파전",
    duration: 20,
    difficulty: "중간",
    servings: "2인분",
    tag: "🥞 바삭 담백",
    ingredients: [
      { name: "쪽파", amount: "100g" },
      { name: "모듬 해물", amount: "100g" },
      { name: "부침가루", amount: "1컵 (100g)" },
      { name: "물", amount: "150ml" },
      { name: "계란", amount: "1개" },
      { name: "식용유", amount: "3큰술" },
    ],
    steps: [
      "쪽파는 팬 크기에 맞춰 반으로 자르고, 해물은 씻어 물기를 빼 둡니다.",
      "볼에 부침가루와 물 150ml를 섞어 반죽을 만듭니다.",
      "팬에 식용유를 넉넉히 두르고 쪽파를 고르게 깔아 반죽을 붓습니다.",
      "해물을 골고루 올리고 중불에서 3~4분 굽습니다.",
      "계란을 풀어 위에 뿌린 뒤 뒤집어 반대편도 3분 굽습니다.",
      "간장 소스에 찍어 바삭하게 냅니다.",
    ],
    image: "/images/pancake.png",
    matchIngredients: ["쪽파", "해물", "부침가루", "계란"],
  },
  {
    id: "miyeok-guk",
    name: "미역국",
    duration: 20,
    difficulty: "쉬움",
    servings: "2인분",
    tag: "🌊 시원한 국물",
    ingredients: [
      { name: "미역", amount: "20g (불린 것 150g)" },
      { name: "소고기 (양지)", amount: "100g" },
      { name: "다진마늘", amount: "1작은술" },
      { name: "국간장", amount: "1.5큰술" },
      { name: "참기름", amount: "1큰술" },
      { name: "물", amount: "800ml (종이컵 약 4컵)" },
    ],
    steps: [
      "미역은 찬물에 20분 불려 물기를 꼭 짠 뒤 먹기 좋은 크기로 썹니다.",
      "냄비에 참기름을 두르고 소고기를 볶다가 미역을 넣어 함께 2분간 볶습니다.",
      "물 800ml를 붓고 강불로 끓입니다. 끓으면 거품을 걷어냅니다.",
      "국간장과 다진마늘을 넣고 중불에서 10분간 더 끓입니다.",
      "소금으로 간을 맞추고 완성합니다.",
    ],
    image: "/images/soup.png",
    matchIngredients: ["미역", "소고기", "마늘", "국간장"],
  },
  {
    id: "galbitan",
    name: "갈비탕",
    duration: 90,
    difficulty: "어려움",
    servings: "2인분",
    tag: "🍖 깊은 국물",
    ingredients: [
      { name: "소갈비", amount: "500g" },
      { name: "무", amount: "150g" },
      { name: "대파", amount: "1대" },
      { name: "다진마늘", amount: "1큰술" },
      { name: "국간장", amount: "1큰술" },
      { name: "물", amount: "1.5L (종이컵 약 7컵)" },
    ],
    steps: [
      "갈비는 찬물에 30분 담가 핏물을 빼고 끓는 물에 5분 데쳐 씻습니다.",
      "냄비에 물 1.5L와 갈비를 넣고 강불로 끓입니다.",
      "끓으면 거품을 걷어내고 중불로 줄여 40분간 끓입니다.",
      "무를 넣고 20분 더 끓입니다.",
      "국간장과 마늘로 간을 맞추고 대파를 넣어 완성합니다.",
    ],
    image: "/images/soup.png",
    matchIngredients: ["소갈비", "무", "대파", "마늘"],
  },
  {
    id: "tteokbokki",
    name: "떡볶이",
    duration: 15,
    difficulty: "쉬움",
    servings: "2인분",
    tag: "🌶️ 쫄깃 달콤",
    ingredients: [
      { name: "가래떡", amount: "200g" },
      { name: "어묵", amount: "2장" },
      { name: "대파", amount: "1/3대" },
      { name: "고추장", amount: "2큰술" },
      { name: "올리고당", amount: "1.5큰술" },
      { name: "간장", amount: "1작은술" },
      { name: "물", amount: "300ml (종이컵 약 1.5컵)" },
    ],
    steps: [
      "떡이 딱딱하면 따뜻한 물에 10분 담가 부드럽게 합니다.",
      "냄비에 물 300ml를 붓고 고추장, 올리고당, 간장을 넣어 섞습니다.",
      "강불로 끓으면 어묵과 떡을 넣습니다.",
      "중불에서 소스가 걸쭉해질 때까지 5~6분간 저어가며 졸입니다.",
      "대파를 넣고 1분 더 끓여 완성합니다.",
    ],
    image: "/images/stir_fried_pork.png",
    matchIngredients: ["가래떡", "어묵", "고추장", "대파"],
  },
  {
    id: "hobak-jeon",
    name: "애호박전",
    duration: 15,
    difficulty: "쉬움",
    servings: "2인분",
    tag: "🫑 담백 전통",
    ingredients: [
      { name: "애호박", amount: "1/2개 (약 150g)" },
      { name: "계란", amount: "2개" },
      { name: "밀가루", amount: "3큰술" },
      { name: "소금", amount: "1/2작은술" },
      { name: "식용유", amount: "3큰술" },
    ],
    steps: [
      "애호박을 0.5cm 두께로 동그랗게 썰어 소금을 뿌려 5분 절입니다.",
      "키친타월로 물기를 꼭 제거합니다.",
      "밀가루를 앞뒤로 얇게 묻히고 계란물에 담급니다.",
      "달군 팬에 식용유를 두르고 중불에서 앞뒤로 2~3분씩 굽습니다.",
      "간장 소스에 찍어 냅니다.",
    ],
    image: "/images/pancake.png",
    matchIngredients: ["애호박", "계란", "밀가루"],
  },

  // ──────────────────────────────────────────
  // 양식 20개
  // ──────────────────────────────────────────
  {
    id: "carbonara",
    name: "까르보나라",
    duration: 20,
    difficulty: "중간",
    servings: "1인분",
    tag: "🇮🇹 크리미 정통",
    ingredients: [
      { name: "스파게티면", amount: "80g" },
      { name: "베이컨", amount: "3줄" },
      { name: "계란 노른자", amount: "2개" },
      { name: "파마산 치즈가루", amount: "3큰술" },
      { name: "후추", amount: "넉넉히" },
      { name: "물", amount: "1L (면 삶기용)" },
    ],
    steps: [
      "냄비에 물 1L와 소금 1큰술을 끓여 스파게티를 7분간 알단테로 삶습니다. (면수 1/2컵 보관)",
      "볼에 계란 노른자 2개, 파마산 치즈가루, 후추를 섞어 소스를 만듭니다.",
      "팬에 기름 없이 베이컨을 노릇하게 볶아 기름을 냅니다.",
      "불을 끄고 삶은 면과 면수 2큰술을 팬에 넣어 고르게 섞습니다.",
      "팬의 열이 살짝 식으면 계란 소스를 붓고 빠르게 저어 크리미하게 완성합니다.",
    ],
    image: "/images/noodle.png",
    matchIngredients: ["스파게티면", "베이컨", "계란", "치즈"],
  },
  {
    id: "tomato-pasta",
    name: "토마토 파스타",
    duration: 20,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🍅 상큼 이탈리안",
    ingredients: [
      { name: "스파게티면", amount: "80g" },
      { name: "토마토소스 (캔)", amount: "200g" },
      { name: "마늘", amount: "3알" },
      { name: "올리브유", amount: "2큰술" },
      { name: "베이컨", amount: "2줄 (선택)" },
      { name: "물", amount: "1L (면 삶기용)" },
    ],
    steps: [
      "냄비에 물 1L를 끓여 스파게티를 7분간 삶습니다. (면수 보관)",
      "마늘은 얇게 슬라이스합니다.",
      "팬에 올리브유를 두르고 마늘을 약불에서 노릇하게 볶아 향을 냅니다.",
      "토마토소스를 붓고 중불에서 3~4분 끓입니다.",
      "삶은 면과 면수 3큰술을 넣고 소스와 잘 섞어 완성합니다.",
    ],
    image: "/images/noodle.png",
    matchIngredients: ["스파게티면", "토마토소스", "마늘", "올리브유"],
  },
  {
    id: "aglio-olio",
    name: "알리오 올리오",
    duration: 15,
    difficulty: "중간",
    servings: "1인분",
    tag: "🧄 심플 정통",
    ingredients: [
      { name: "스파게티면", amount: "80g" },
      { name: "마늘", amount: "5알" },
      { name: "페페론치노", amount: "2~3개" },
      { name: "올리브유", amount: "4큰술" },
      { name: "파슬리 가루", amount: "1작은술" },
      { name: "물", amount: "1L (면 삶기용)" },
    ],
    steps: [
      "냄비에 물 1L와 소금을 끓여 스파게티를 7분간 삶습니다. (면수 1/2컵 보관)",
      "마늘은 얇게 슬라이스합니다.",
      "팬에 올리브유를 넉넉히 두르고 마늘과 페페론치노를 약불에서 천천히 볶습니다.",
      "마늘이 노릇해지면 삶은 면과 면수 3큰술을 넣어 빠르게 버무립니다.",
      "파슬리 가루를 뿌려 완성합니다.",
    ],
    image: "/images/noodle.png",
    matchIngredients: ["스파게티면", "마늘", "올리브유", "페페론치노"],
  },
  {
    id: "rose-pasta",
    name: "로제 파스타",
    duration: 20,
    difficulty: "중간",
    servings: "1인분",
    tag: "🌹 크리미 매콤",
    ingredients: [
      { name: "펜네 또는 스파게티", amount: "80g" },
      { name: "베이컨", amount: "3줄" },
      { name: "토마토소스", amount: "100g" },
      { name: "생크림", amount: "100ml" },
      { name: "마늘", amount: "2알" },
      { name: "고추", amount: "1개 (선택)" },
      { name: "물", amount: "1L" },
    ],
    steps: [
      "냄비에 물 1L를 끓여 면을 7분 삶아 둡니다.",
      "팬에 베이컨을 볶다가 마늘을 추가해 향을 냅니다.",
      "토마토소스를 붓고 2분 끓인 뒤 생크림을 넣어 핑크색 소스를 만듭니다.",
      "삶은 면을 넣고 소스와 잘 섞어 1~2분 더 끓입니다.",
      "소금과 후추로 간하고 치즈 가루를 뿌려 완성합니다.",
    ],
    image: "/images/noodle.png",
    matchIngredients: ["파스타면", "베이컨", "토마토소스", "생크림", "마늘"],
  },
  {
    id: "bacon-egg-toast",
    name: "베이컨 에그 토스트",
    duration: 10,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🥪 든든 아침",
    ingredients: [
      { name: "식빵", amount: "2장" },
      { name: "베이컨", amount: "2줄" },
      { name: "계란", amount: "1개" },
      { name: "치즈 슬라이스", amount: "1장" },
      { name: "버터", amount: "10g" },
      { name: "케첩", amount: "적당량" },
    ],
    steps: [
      "팬에 버터를 녹이고 식빵 2장을 앞뒤로 노릇하게 구워 둡니다.",
      "같은 팬에 베이컨을 노릇하게 굽습니다.",
      "계란 프라이를 만들어 취향에 따라 반숙 또는 완숙으로 익힙니다.",
      "구운 식빵 위에 치즈, 베이컨, 계란 순서로 올립니다.",
      "케첩을 뿌리고 다른 식빵으로 덮어 완성합니다.",
    ],
    image: "/images/toast.png",
    matchIngredients: ["식빵", "베이컨", "계란", "치즈", "버터"],
  },
  {
    id: "club-sandwich",
    name: "클럽 샌드위치",
    duration: 15,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🥗 풍성 샌드위치",
    ingredients: [
      { name: "식빵", amount: "3장" },
      { name: "닭가슴살", amount: "80g" },
      { name: "베이컨", amount: "2줄" },
      { name: "양상추", amount: "2장" },
      { name: "토마토", amount: "1/2개" },
      { name: "마요네즈", amount: "2큰술" },
    ],
    steps: [
      "식빵 3장을 토스터에 노릇하게 굽습니다.",
      "닭가슴살은 삶아 얇게 썰고, 베이컨은 굽습니다.",
      "토마토는 얇게 슬라이스합니다.",
      "식빵에 마요네즈를 바르고 양상추, 닭가슴살을 올립니다.",
      "두 번째 식빵, 베이컨, 토마토, 세 번째 식빵 순서로 쌓아 완성합니다.",
    ],
    image: "/images/toast.png",
    matchIngredients: ["식빵", "닭가슴살", "베이컨", "양상추", "토마토"],
  },
  {
    id: "omelette",
    name: "오믈렛",
    duration: 10,
    difficulty: "중간",
    servings: "1인분",
    tag: "🍳 촉촉 부드러움",
    ingredients: [
      { name: "계란", amount: "3개" },
      { name: "버터", amount: "15g" },
      { name: "우유", amount: "2큰술" },
      { name: "치즈 슬라이스", amount: "1장" },
      { name: "소금", amount: "약간" },
      { name: "후추", amount: "약간" },
    ],
    steps: [
      "계란 3개에 우유, 소금, 후추를 넣고 잘 풀어줍니다.",
      "팬에 버터를 녹이고 중약불로 줄입니다.",
      "계란물을 붓고 젓가락으로 빠르게 저어 스크램블 반숙 상태를 만듭니다.",
      "치즈를 가운데 올리고 반으로 접어 타원형 오믈렛을 만듭니다.",
      "접시에 옮겨 토마토케첩을 곁들여 냅니다.",
    ],
    image: "/images/egg_roll.png",
    matchIngredients: ["계란", "버터", "우유", "치즈"],
  },
  {
    id: "scrambled-eggs",
    name: "스크램블 에그",
    duration: 8,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "⚡ 촉촉 고소",
    ingredients: [
      { name: "계란", amount: "3개" },
      { name: "버터", amount: "15g" },
      { name: "우유 또는 생크림", amount: "2큰술" },
      { name: "소금", amount: "약간" },
      { name: "후추", amount: "약간" },
    ],
    steps: [
      "계란, 우유, 소금, 후추를 볼에 넣고 잘 섞습니다.",
      "팬에 버터를 넣고 약불로 달굽니다.",
      "계란물을 붓고 젓가락으로 천천히 부드럽게 저어줍니다.",
      "반 정도 굳으면 불을 끄고 잔열로 원하는 굳기까지 마저 익힙니다.",
      "토스트 위에 올려 냅니다.",
    ],
    image: "/images/egg_roll.png",
    matchIngredients: ["계란", "버터", "우유"],
  },
  {
    id: "pancakes",
    name: "팬케이크",
    duration: 20,
    difficulty: "쉬움",
    servings: "2인분 (6장)",
    tag: "🥞 달콤 폭신",
    ingredients: [
      { name: "박력분", amount: "150g" },
      { name: "계란", amount: "1개" },
      { name: "우유", amount: "150ml" },
      { name: "베이킹파우더", amount: "1작은술" },
      { name: "설탕", amount: "1큰술" },
      { name: "버터", amount: "10g" },
    ],
    steps: [
      "볼에 박력분, 베이킹파우더, 설탕을 체에 쳐 섞습니다.",
      "계란, 우유, 녹인 버터를 넣고 덩어리가 없도록 섞습니다. (너무 많이 저으면 쫄깃해짐)",
      "팬을 약불로 달구고 반죽을 떠서 지름 10cm 크기로 붓습니다.",
      "표면에 기포가 생기면 뒤집어 반대편도 2분 굽습니다.",
      "메이플시럽이나 버터를 올려 냅니다.",
    ],
    image: "/images/pancake.png",
    matchIngredients: ["박력분", "계란", "우유", "버터"],
  },
  {
    id: "french-toast",
    name: "프렌치 토스트",
    duration: 12,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🍞 달콤 촉촉",
    ingredients: [
      { name: "두꺼운 식빵", amount: "2장" },
      { name: "계란", amount: "2개" },
      { name: "우유", amount: "3큰술" },
      { name: "설탕", amount: "1큰술" },
      { name: "버터", amount: "15g" },
      { name: "시나몬 가루", amount: "약간 (선택)" },
    ],
    steps: [
      "볼에 계란, 우유, 설탕, 시나몬을 섞어 계란물을 만듭니다.",
      "식빵을 계란물에 앞뒤로 충분히 적셔 줍니다.",
      "팬에 버터를 녹이고 중약불에서 식빵을 올립니다.",
      "앞뒤로 각 2~3분씩 노릇하게 굽습니다.",
      "메이플시럽이나 슈가파우더를 뿌려 냅니다.",
    ],
    image: "/images/toast.png",
    matchIngredients: ["식빵", "계란", "우유", "버터", "설탕"],
  },
  {
    id: "chicken-salad",
    name: "그릴드 치킨 샐러드",
    duration: 20,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🥗 가볍고 든든",
    ingredients: [
      { name: "닭가슴살", amount: "150g" },
      { name: "양상추", amount: "100g" },
      { name: "방울토마토", amount: "8개" },
      { name: "오이", amount: "1/3개" },
      { name: "올리브유", amount: "1큰술" },
      { name: "발사믹 드레싱", amount: "2큰술" },
    ],
    steps: [
      "닭가슴살에 소금, 후추, 올리브유를 발라 10분 재웁니다.",
      "팬을 중강불로 달궈 닭가슴살 앞뒤로 각 4~5분 구워 완전히 익힙니다.",
      "닭가슴살을 5분간 식힌 뒤 결대로 찢거나 얇게 썹니다.",
      "양상추, 방울토마토, 오이를 넓은 그릇에 담습니다.",
      "닭가슴살을 올리고 발사믹 드레싱을 뿌려 냅니다.",
    ],
    image: "/images/salad.png",
    matchIngredients: ["닭가슴살", "양상추", "토마토", "오이"],
  },
  {
    id: "hamburger-steak",
    name: "함박스테이크",
    duration: 30,
    difficulty: "중간",
    servings: "2인분",
    tag: "🍔 든든 양식",
    ingredients: [
      { name: "다진 소고기+돼지고기", amount: "300g" },
      { name: "양파", amount: "1/4개" },
      { name: "계란", amount: "1개" },
      { name: "빵가루", amount: "3큰술" },
      { name: "우유", amount: "2큰술" },
      { name: "케첩", amount: "2큰술" },
      { name: "돈가스 소스", amount: "2큰술" },
    ],
    steps: [
      "양파를 잘게 다져 팬에 볶아 식힙니다.",
      "볼에 다진 고기, 볶은 양파, 계란, 우유에 적신 빵가루를 넣고 치대어 반죽합니다.",
      "2등분해 타원형으로 빚고 가운데를 살짝 눌러 줍니다.",
      "달군 팬에 식용유를 두르고 앞뒤로 각 4~5분씩 노릇하게 굽습니다.",
      "케첩과 돈가스 소스를 섞어 뿌려 완성합니다.",
    ],
    image: "/images/grilled.png",
    matchIngredients: ["다진소고기", "다진돼지고기", "양파", "계란", "빵가루"],
  },
  {
    id: "cream-risotto",
    name: "크림 리조또",
    duration: 30,
    difficulty: "중간",
    servings: "1인분",
    tag: "🍚 고소 크리미",
    ingredients: [
      { name: "아보리오 쌀 (또는 밥)", amount: "80g (쌀) / 200g (밥)" },
      { name: "양파", amount: "1/4개" },
      { name: "버터", amount: "20g" },
      { name: "생크림", amount: "100ml" },
      { name: "파마산 치즈가루", amount: "3큰술" },
      { name: "닭고기 육수", amount: "400ml" },
    ],
    steps: [
      "양파를 잘게 다져 버터와 함께 팬에서 투명해질 때까지 볶습니다.",
      "쌀을 넣고 1~2분 볶아 기름을 코팅합니다.",
      "육수를 2~3번에 나눠 넣으며 쌀이 육수를 흡수할 때마다 저어줍니다. (약 20분)",
      "생크림과 치즈가루를 넣고 부드럽게 섞어 완성합니다.",
    ],
    image: "/images/noodle.png",
    matchIngredients: ["쌀", "양파", "버터", "생크림", "치즈"],
  },
  {
    id: "tomato-soup",
    name: "토마토 수프",
    duration: 25,
    difficulty: "쉬움",
    servings: "2인분",
    tag: "🍅 따뜻 수프",
    ingredients: [
      { name: "토마토 (또는 캔)", amount: "400g" },
      { name: "양파", amount: "1/2개" },
      { name: "마늘", amount: "2알" },
      { name: "올리브유", amount: "2큰술" },
      { name: "닭고기 육수", amount: "300ml" },
      { name: "생크림", amount: "50ml" },
    ],
    steps: [
      "양파와 마늘을 잘게 다져 올리브유와 함께 5분간 볶습니다.",
      "토마토를 넣고 5분간 더 볶습니다.",
      "육수 300ml를 붓고 15분간 끓입니다.",
      "핸드 블렌더로 곱게 갈아 체에 거릅니다.",
      "생크림을 두르고 소금과 후추로 간하여 완성합니다.",
    ],
    image: "/images/soup.png",
    matchIngredients: ["토마토", "양파", "마늘", "생크림"],
  },
  {
    id: "onion-soup",
    name: "프렌치 어니언 수프",
    duration: 40,
    difficulty: "중간",
    servings: "2인분",
    tag: "🧅 깊은 양식",
    ingredients: [
      { name: "양파", amount: "2개 (대)" },
      { name: "버터", amount: "30g" },
      { name: "소고기 육수", amount: "500ml" },
      { name: "레드와인", amount: "2큰술 (선택)" },
      { name: "바게트빵", amount: "2조각" },
      { name: "그뤼에르 치즈", amount: "50g" },
    ],
    steps: [
      "양파를 얇게 채 썰어 버터와 함께 약불에서 30분간 갈색이 될 때까지 천천히 볶습니다.",
      "레드와인을 넣고 1분간 알코올을 날립니다.",
      "육수 500ml를 붓고 10분간 끓입니다. 소금과 후추로 간합니다.",
      "수프를 오븐용 그릇에 담고 바게트와 치즈를 올립니다.",
      "오븐 200도에서 치즈가 녹고 노릇해질 때까지 10분 굽습니다.",
    ],
    image: "/images/soup.png",
    matchIngredients: ["양파", "버터", "소고기 육수", "바게트빵", "치즈"],
  },
  {
    id: "gratin",
    name: "감자 그라탕",
    duration: 45,
    difficulty: "중간",
    servings: "2인분",
    tag: "🧀 구운 치즈",
    ingredients: [
      { name: "감자", amount: "2개 (약 300g)" },
      { name: "생크림", amount: "150ml" },
      { name: "모짜렐라 치즈", amount: "80g" },
      { name: "버터", amount: "10g" },
      { name: "마늘", amount: "1알" },
      { name: "소금", amount: "약간" },
    ],
    steps: [
      "감자를 0.3cm로 얇게 슬라이스합니다.",
      "오븐 용기에 버터를 바르고 마늘로 문질러 향을 냅니다.",
      "감자를 겹겹이 쌓고 생크림을 부은 뒤 소금, 후추로 간합니다.",
      "모짜렐라 치즈를 올립니다.",
      "오븐 180도에서 30~35분 구워 치즈가 노릇하게 익으면 완성합니다.",
    ],
    image: "/images/toast.png",
    matchIngredients: ["감자", "생크림", "치즈", "버터"],
  },
  {
    id: "avocado-salad",
    name: "아보카도 샐러드",
    duration: 10,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🥑 건강 그린",
    ingredients: [
      { name: "아보카도", amount: "1개" },
      { name: "방울토마토", amount: "8개" },
      { name: "양상추", amount: "80g" },
      { name: "레몬즙", amount: "1큰술" },
      { name: "올리브유", amount: "1큰술" },
      { name: "소금", amount: "약간" },
    ],
    steps: [
      "아보카도를 반으로 갈라 씨를 제거하고 껍질을 벗겨 슬라이스합니다.",
      "레몬즙을 뿌려 갈변을 방지합니다.",
      "방울토마토는 반으로 자르고, 양상추는 먹기 좋게 뜯어 준비합니다.",
      "드레싱: 올리브유, 레몬즙, 소금, 후추를 섞습니다.",
      "모든 재료를 담고 드레싱을 뿌려 냅니다.",
    ],
    image: "/images/salad.png",
    matchIngredients: ["아보카도", "방울토마토", "양상추"],
  },
  {
    id: "pork-cutlet",
    name: "포크 커틀렛",
    duration: 25,
    difficulty: "중간",
    servings: "1인분",
    tag: "🍖 바삭 육즙",
    ingredients: [
      { name: "돼지고기 등심", amount: "150g (두꺼운 것)" },
      { name: "밀가루", amount: "적당량" },
      { name: "계란", amount: "1개" },
      { name: "빵가루", amount: "적당량" },
      { name: "튀김 기름", amount: "400ml" },
      { name: "돈가스 소스", amount: "적당량" },
    ],
    steps: [
      "고기는 1.5cm 두께로 근막을 칼등으로 두드려 연육합니다.",
      "소금, 후추로 밑간합니다.",
      "밀가루 → 풀어둔 계란 → 빵가루 순서로 골고루 묻힙니다.",
      "기름을 170도로 가열해 고기를 4~5분간 노릇하게 튀깁니다.",
      "건져서 기름을 제거하고 돈가스 소스를 곁들여 냅니다.",
    ],
    image: "/images/chicken.png",
    matchIngredients: ["돼지고기", "밀가루", "계란", "빵가루"],
  },
  {
    id: "garlic-butter-shrimp",
    name: "갈릭 버터 새우 구이",
    duration: 15,
    difficulty: "쉬움",
    servings: "2인분",
    tag: "🍤 향긋 고소",
    ingredients: [
      { name: "새우 (중형)", amount: "200g" },
      { name: "버터", amount: "25g" },
      { name: "마늘", amount: "5알" },
      { name: "파슬리 가루", amount: "1작은술" },
      { name: "소금", amount: "약간" },
      { name: "레몬", amount: "1/2개" },
    ],
    steps: [
      "새우는 껍질을 벗기고 등 쪽 내장을 제거합니다.",
      "마늘은 얇게 슬라이스합니다.",
      "팬에 버터를 녹이고 마늘을 넣어 향을 냅니다.",
      "새우를 넣어 앞뒤로 2분씩 구워 완전히 익힙니다.",
      "파슬리 가루와 소금으로 마무리하고 레몬즙을 뿌려 냅니다.",
    ],
    image: "/images/grilled.png",
    matchIngredients: ["새우", "버터", "마늘", "레몬"],
  },

  // ──────────────────────────────────────────
  // 일식 20개
  // ──────────────────────────────────────────
  {
    id: "tonkatsu",
    name: "돈카츠",
    duration: 25,
    difficulty: "중간",
    servings: "1인분",
    tag: "🇯🇵 바삭 정통",
    ingredients: [
      { name: "돼지고기 등심", amount: "150g" },
      { name: "밀가루", amount: "적당량" },
      { name: "계란", amount: "1개" },
      { name: "빵가루", amount: "50g" },
      { name: "식용유", amount: "400ml" },
      { name: "돈카츠 소스", amount: "적당량" },
    ],
    steps: [
      "돼지고기는 힘줄과 지방 경계를 칼로 3~4군데 끊어 쫄깃하게 만들고 두드려 연육합니다.",
      "소금, 후추로 앞뒤 밑간합니다.",
      "밀가루 → 계란물 → 빵가루 순서로 골고루 묻힙니다.",
      "기름을 170도로 달궈 고기를 넣어 3~4분 튀깁니다.",
      "기름 온도를 180도로 올려 30초간 더 튀겨 바삭하게 합니다.",
      "기름을 빼고 돈카츠 소스, 양배추 채를 곁들여 냅니다.",
    ],
    image: "/images/chicken.png",
    matchIngredients: ["돼지고기", "밀가루", "계란", "빵가루"],
  },
  {
    id: "ramen",
    name: "라멘",
    duration: 15,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🍜 진한 국물",
    ingredients: [
      { name: "라면 봉지", amount: "1개" },
      { name: "계란", amount: "1개" },
      { name: "대파", amount: "1/4대" },
      { name: "차슈 (또는 삼겹살)", amount: "50g (선택)" },
      { name: "물", amount: "550ml (종이컵 약 2.5컵)" },
    ],
    steps: [
      "냄비에 물 550ml를 강불로 끓입니다.",
      "팔팔 끓으면 라면 스프와 면을 동시에 넣습니다.",
      "면을 젓가락으로 풀어가며 3~4분간 끓입니다.",
      "계란을 깨뜨려 넣고 반숙이 되도록 1~2분 더 끓입니다.",
      "그릇에 담고 대파와 차슈를 올려 냅니다.",
    ],
    image: "/images/noodle.png",
    matchIngredients: ["라면", "계란", "대파"],
  },
  {
    id: "udon",
    name: "우동",
    duration: 15,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🍢 쫄깃 국물",
    ingredients: [
      { name: "우동면 (냉동)", amount: "1팩" },
      { name: "대파", amount: "1/3대" },
      { name: "어묵", amount: "1장" },
      { name: "쯔유", amount: "3큰술" },
      { name: "물", amount: "500ml (종이컵 약 2.5컵)" },
    ],
    steps: [
      "냄비에 물 500ml를 끓여 쯔유 3큰술을 넣어 육수를 만듭니다.",
      "육수가 끓으면 우동면을 넣어 1~2분간 끓여 풀어줍니다.",
      "어묵을 먹기 좋게 잘라 함께 넣고 2분 더 끓입니다.",
      "그릇에 담고 대파를 올려 완성합니다.",
    ],
    image: "/images/noodle.png",
    matchIngredients: ["우동면", "대파", "어묵", "쯔유"],
  },
  {
    id: "soba",
    name: "자루 소바",
    duration: 10,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🍝 시원 담백",
    ingredients: [
      { name: "소바면 (메밀면)", amount: "100g" },
      { name: "쯔유", amount: "3큰술" },
      { name: "물 (차가운 것)", amount: "200ml" },
      { name: "대파", amount: "약간" },
      { name: "김가루", amount: "약간" },
      { name: "와사비", amount: "약간" },
    ],
    steps: [
      "냄비에 충분한 물을 끓여 소바면을 5~6분간 삶습니다.",
      "삶은 면을 찬물에 빠르게 헹궈 전분을 완전히 제거하고 얼음으로 식힙니다.",
      "쯔유와 찬물을 3:1 비율로 섞어 소스를 만듭니다.",
      "그릇에 소바를 담고 김가루를 뿌립니다.",
      "대파, 와사비를 소스에 취향대로 넣어 찍어 먹습니다.",
    ],
    image: "/images/noodle.png",
    matchIngredients: ["소바면", "쯔유", "대파", "와사비"],
  },
  {
    id: "oyakodon",
    name: "오야코동",
    duration: 20,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🐔 부드러운 덮밥",
    ingredients: [
      { name: "닭고기 허벅지살", amount: "150g" },
      { name: "계란", amount: "2개" },
      { name: "양파", amount: "1/4개" },
      { name: "간장", amount: "2큰술" },
      { name: "미림", amount: "1큰술" },
      { name: "설탕", amount: "1작은술" },
      { name: "물", amount: "100ml" },
      { name: "밥", amount: "300g" },
    ],
    steps: [
      "닭고기를 한 입 크기로 썰고, 양파는 채 썹니다.",
      "작은 냄비에 물 100ml, 간장, 미림, 설탕을 넣고 끓입니다.",
      "양파를 넣어 2분 익힌 뒤 닭고기를 넣어 3~4분 익힙니다.",
      "계란 2개를 풀어 반만 두르고 반 정도 익으면 나머지를 두릅니다.",
      "반숙 상태에서 불을 끄고 따뜻한 밥 위에 올립니다.",
    ],
    image: "/images/jeyuk_deopbap.png",
    matchIngredients: ["닭고기", "계란", "양파", "간장", "밥"],
  },
  {
    id: "gyudon",
    name: "규동 (소고기 덮밥)",
    duration: 20,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🥩 달콤 고기덮밥",
    ingredients: [
      { name: "소고기 (샤부샤부용)", amount: "150g" },
      { name: "양파", amount: "1/4개" },
      { name: "간장", amount: "2큰술" },
      { name: "미림", amount: "2큰술" },
      { name: "설탕", amount: "1작은술" },
      { name: "물", amount: "100ml" },
      { name: "밥", amount: "300g" },
    ],
    steps: [
      "양파를 채 썰고, 소고기는 먹기 좋은 크기로 준비합니다.",
      "냄비에 물 100ml, 간장, 미림, 설탕을 넣고 끓입니다.",
      "양파를 넣어 2~3분 익힙니다.",
      "소고기를 넣어 색이 변할 때까지 2분 더 끓입니다.",
      "따뜻한 밥 위에 얹어 냅니다.",
    ],
    image: "/images/jeyuk_deopbap.png",
    matchIngredients: ["소고기", "양파", "간장", "미림", "밥"],
  },
  {
    id: "curry-rice",
    name: "카레라이스",
    duration: 30,
    difficulty: "쉬움",
    servings: "2인분",
    tag: "🍛 향긋 카레",
    ingredients: [
      { name: "고형 카레", amount: "2조각" },
      { name: "감자", amount: "1개" },
      { name: "당근", amount: "1/2개" },
      { name: "양파", amount: "1개" },
      { name: "닭고기 또는 소고기", amount: "150g" },
      { name: "물", amount: "400ml (종이컵 약 2컵)" },
      { name: "밥", amount: "적당량" },
    ],
    steps: [
      "감자, 당근, 양파, 고기를 한 입 크기로 씁니다.",
      "냄비에 식용유를 두르고 고기와 양파를 볶습니다.",
      "감자와 당근을 넣고 1~2분 더 볶습니다.",
      "물 400ml를 붓고 끓으면 거품을 걷어 중불에서 15분 끓입니다.",
      "불을 줄이고 고형 카레를 녹여 5분간 저어가며 익혀 밥과 함께 냅니다.",
    ],
    image: "/images/jeyuk_deopbap.png",
    matchIngredients: ["카레", "감자", "당근", "양파"],
  },
  {
    id: "omurice",
    name: "오므라이스",
    duration: 20,
    difficulty: "중간",
    servings: "1인분",
    tag: "🍳 달걀 덮밥",
    ingredients: [
      { name: "밥", amount: "250g" },
      { name: "계란", amount: "3개" },
      { name: "닭고기", amount: "80g" },
      { name: "양파", amount: "1/4개" },
      { name: "케첩", amount: "3큰술" },
      { name: "버터", amount: "15g" },
    ],
    steps: [
      "닭고기와 양파를 잘게 다집니다.",
      "팬에 버터를 녹이고 닭고기, 양파를 볶아 익으면 밥과 케첩 2큰술을 넣어 볶아 케첩 볶음밥을 만듭니다.",
      "계란 3개에 우유 1큰술을 넣고 풀어 둡니다.",
      "새 팬에 버터를 녹이고 계란물을 부어 젓가락으로 빠르게 저어 반숙 오믈렛을 만들며 볶음밥을 감쌉니다.",
      "접시에 담고 케첩을 뿌려 냅니다.",
    ],
    image: "/images/egg_roll.png",
    matchIngredients: ["밥", "계란", "닭고기", "양파", "케첩"],
  },
  {
    id: "tendon",
    name: "텐동 (튀김 덮밥)",
    duration: 25,
    difficulty: "중간",
    servings: "1인분",
    tag: "🍤 바삭 덮밥",
    ingredients: [
      { name: "새우", amount: "4마리" },
      { name: "고구마", amount: "1/3개" },
      { name: "튀김가루", amount: "100g" },
      { name: "물 (얼음물)", amount: "120ml" },
      { name: "간장", amount: "2큰술" },
      { name: "미림", amount: "2큰술" },
      { name: "밥", amount: "300g" },
      { name: "튀김 기름", amount: "적당량" },
    ],
    steps: [
      "새우 껍질을 벗겨 꼬리만 남기고 내장을 제거합니다. 고구마는 5mm로 얇게 썹니다.",
      "볼에 튀김가루와 얼음물 120ml를 덩어리가 남도록 가볍게 섞어 반죽합니다.",
      "170~180도 기름에 반죽을 입힌 새우와 고구마를 바삭하게 튀깁니다.",
      "간장, 미림, 물 2큰술을 끓여 텐동 소스를 만듭니다.",
      "밥 위에 튀김을 얹고 소스를 뿌려 냅니다.",
    ],
    image: "/images/chicken.png",
    matchIngredients: ["새우", "고구마", "튀김가루", "밥"],
  },
  {
    id: "karaage",
    name: "가라아게 (일본식 치킨)",
    duration: 30,
    difficulty: "중간",
    servings: "2인분",
    tag: "🍗 바삭 쫄깃",
    ingredients: [
      { name: "닭 허벅지살", amount: "300g" },
      { name: "간장", amount: "2큰술" },
      { name: "미림", amount: "1큰술" },
      { name: "생강즙", amount: "1작은술" },
      { name: "다진마늘", amount: "1작은술" },
      { name: "감자전분", amount: "4큰술" },
      { name: "튀김 기름", amount: "적당량" },
    ],
    steps: [
      "닭고기를 한 입 크기로 썰고 간장, 미림, 생강즙, 마늘로 15분 이상 재웁니다.",
      "재운 닭고기에 감자전분을 골고루 묻힙니다.",
      "기름을 170도로 달궈 닭고기를 넣어 3~4분 튀깁니다.",
      "건져 1분 휴지 후, 기름 온도를 180도로 올려 1분간 다시 바삭하게 튀깁니다.",
      "레몬과 마요네즈를 곁들여 냅니다.",
    ],
    image: "/images/chicken.png",
    matchIngredients: ["닭고기", "간장", "미림", "생강", "마늘"],
  },
  {
    id: "miso-soup",
    name: "미소시루 (된장국)",
    duration: 10,
    difficulty: "쉬움",
    servings: "2인분",
    tag: "🌿 일본 가정식",
    ingredients: [
      { name: "미소 (일본 된장)", amount: "2큰술" },
      { name: "두부", amount: "1/4모" },
      { name: "건미역", amount: "2g" },
      { name: "다시마 가쓰오 육수", amount: "400ml (종이컵 약 2컵)" },
      { name: "쪽파", amount: "약간" },
    ],
    steps: [
      "건미역을 찬물에 불려 두고, 두부는 1cm 사각형으로 썹니다.",
      "냄비에 육수 400ml를 넣고 끓입니다.",
      "불린 미역과 두부를 넣고 1~2분 끓입니다.",
      "불을 약하게 줄이고 미소를 국자에 넣어 육수에 천천히 풀어 넣습니다. (끓이지 않아야 향이 살아남)",
      "쪽파를 올려 완성합니다.",
    ],
    image: "/images/soup.png",
    matchIngredients: ["된장", "두부", "미역", "쪽파"],
  },
  {
    id: "yakisoba",
    name: "야키소바",
    duration: 15,
    difficulty: "쉬움",
    servings: "1~2인분",
    tag: "🍜 철판 볶음면",
    ingredients: [
      { name: "야키소바면 (냉동)", amount: "1팩" },
      { name: "돼지고기 삼겹살", amount: "100g" },
      { name: "양배추", amount: "80g" },
      { name: "당근", amount: "1/4개" },
      { name: "야키소바 소스", amount: "2큰술" },
      { name: "가쓰오부시", amount: "약간" },
    ],
    steps: [
      "돼지고기는 한 입 크기로, 양배추와 당근은 채 썰어 준비합니다.",
      "달군 팬에 식용유를 두르고 고기를 볶아 익힙니다.",
      "야채를 넣고 2분간 함께 볶습니다.",
      "냉동 소바면을 넣고 야키소바 소스를 뿌려 강불에서 1~2분 볶습니다.",
      "가쓰오부시와 마요네즈를 올려 완성합니다.",
    ],
    image: "/images/noodle.png",
    matchIngredients: ["소바면", "돼지고기", "양배추", "당근"],
  },
  {
    id: "chahan",
    name: "차한 (일본식 볶음밥)",
    duration: 10,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "🍚 고슬 불향",
    ingredients: [
      { name: "밥", amount: "250g (차가운 것)" },
      { name: "계란", amount: "2개" },
      { name: "대파", amount: "1/4대" },
      { name: "간장", amount: "1작은술" },
      { name: "굴소스", amount: "1작은술" },
      { name: "식용유", amount: "1.5큰술" },
    ],
    steps: [
      "대파를 잘게 다지고, 계란을 풀어 둡니다.",
      "강불로 달군 팬에 기름을 두르고 계란물을 부어 빠르게 스크램블합니다.",
      "계란이 반쯤 익으면 차가운 밥을 넣고 주걱으로 빠르게 눌러가며 볶습니다.",
      "간장과 굴소스를 가장자리에 두르고 대파를 넣어 30초간 강불에서 마무리합니다.",
    ],
    image: "/images/kimchi_fried_rice.png",
    matchIngredients: ["밥", "계란", "대파", "간장"],
  },
  {
    id: "nabe",
    name: "유도후 나베 (두부 전골)",
    duration: 20,
    difficulty: "쉬움",
    servings: "2인분",
    tag: "🍲 따뜻 전골",
    ingredients: [
      { name: "두부 (연두부)", amount: "1모" },
      { name: "백다시마", amount: "10cm 조각 1개" },
      { name: "쯔유", amount: "4큰술" },
      { name: "물", amount: "600ml" },
      { name: "실파", amount: "약간" },
      { name: "간 생강", amount: "1작은술" },
    ],
    steps: [
      "냄비에 물 600ml와 다시마를 넣고 20분간 우려 육수를 만듭니다.",
      "두부를 한 입 크기로 넣고 약불에서 두부가 데워질 때까지 끓입니다.",
      "쯔유를 쪽파, 생강과 함께 작은 종지에 담아 소스를 준비합니다.",
      "따뜻하게 데워진 두부를 소스에 찍어 먹습니다.",
    ],
    image: "/images/soup.png",
    matchIngredients: ["두부", "다시마", "쯔유", "생강"],
  },
  {
    id: "sukiyaki",
    name: "스키야키",
    duration: 25,
    difficulty: "중간",
    servings: "2인분",
    tag: "🥩 달콤 전골",
    ingredients: [
      { name: "소고기 (샤부용)", amount: "200g" },
      { name: "배추", amount: "150g" },
      { name: "두부", amount: "1/2모" },
      { name: "쑥갓", amount: "50g" },
      { name: "간장", amount: "3큰술" },
      { name: "미림", amount: "3큰술" },
      { name: "설탕", amount: "1.5큰술" },
      { name: "물", amount: "100ml" },
    ],
    steps: [
      "냄비에 설탕을 녹이다가 소고기를 먼저 노릇하게 구워냅니다.",
      "간장, 미림, 물 100ml를 넣어 와리시타(양념 육수)를 만듭니다.",
      "배추, 두부 등 채소를 보기 좋게 담고 와리시타를 부어 끓입니다.",
      "마지막에 쑥갓을 올려 살짝 데쳐먹고, 날계란을 찍어먹으면 더 맛있습니다.",
    ],
    image: "/images/soup.png",
    matchIngredients: ["소고기", "배추", "두부", "간장", "미림"],
  },
  {
    id: "onigiri",
    name: "오니기리 (주먹밥)",
    duration: 10,
    difficulty: "쉬움",
    servings: "2인분 (4개)",
    tag: "🍙 간식 도시락",
    ingredients: [
      { name: "밥", amount: "400g (따뜻한 것)" },
      { name: "참치캔", amount: "1/2캔" },
      { name: "마요네즈", amount: "1큰술" },
      { name: "소금", amount: "약간" },
      { name: "김", amount: "2장" },
    ],
    steps: [
      "참치의 기름을 빼고 마요네즈와 섞어 소를 만듭니다.",
      "따뜻한 밥에 소금을 약간 넣어 간합니다.",
      "손에 물을 묻히고 밥을 손바닥에 펼쳐 참치 소를 가운데 올립니다.",
      "삼각형 또는 둥근 모양으로 꽉 쥐어 모양을 잡습니다.",
      "김으로 감싸 완성합니다.",
    ],
    image: "/images/kimchi_fried_rice.png",
    matchIngredients: ["밥", "참치캔", "마요네즈", "김"],
  },
  {
    id: "takoyaki",
    name: "타코야키",
    duration: 30,
    difficulty: "어려움",
    servings: "2인분 (12개)",
    tag: "🐙 바삭 쫄깃",
    ingredients: [
      { name: "문어 (삶은 것)", amount: "80g" },
      { name: "박력분", amount: "100g" },
      { name: "계란", amount: "1개" },
      { name: "다시 육수 또는 물", amount: "250ml" },
      { name: "타코야키 소스", amount: "적당량" },
      { name: "마요네즈", amount: "적당량" },
      { name: "가쓰오부시", amount: "적당량" },
    ],
    steps: [
      "박력분, 계란, 육수 250ml를 섞어 묽은 반죽을 만듭니다.",
      "타코야키 팬을 달궈 기름을 충분히 바릅니다.",
      "반죽을 80% 정도 채우고 문어를 각 칸에 하나씩 넣습니다.",
      "바닥이 굳으면 꼬치로 돌려가며 구슬 모양으로 만들어 3~4분 더 굽습니다.",
      "소스, 마요네즈, 가쓰오부시를 올려 냅니다.",
    ],
    image: "/images/pancake.png",
    matchIngredients: ["문어", "박력분", "계란"],
  },
  {
    id: "cold-soba",
    name: "자루소바 (냉소바)",
    duration: 10,
    difficulty: "쉬움",
    servings: "1인분",
    tag: "❄️ 시원 새콤",
    ingredients: [
      { name: "메밀면", amount: "100g" },
      { name: "쯔유 (진한 것)", amount: "3큰술" },
      { name: "찬물 또는 얼음물", amount: "150ml" },
      { name: "와사비", amount: "약간" },
      { name: "파", amount: "약간" },
    ],
    steps: [
      "냄비에 충분한 물을 끓여 메밀면을 5분간 삶습니다.",
      "삶은 면을 체에 밭쳐 냉수로 빠르게 헹궈 전분을 제거하고 얼음으로 냉각합니다.",
      "쯔유와 찬물을 섞어 소바 소스를 준비합니다.",
      "채반 또는 그릇에 소바를 담습니다.",
      "와사비와 파를 소스에 풀어 면을 찍어 먹습니다.",
    ],
    image: "/images/noodle.png",
    matchIngredients: ["메밀면", "쯔유", "와사비"],
  },
  {
    id: "gyoza",
    name: "교자 (군만두)",
    duration: 30,
    difficulty: "중간",
    servings: "2인분 (16개)",
    tag: "🥟 바삭 고소",
    ingredients: [
      { name: "만두피", amount: "16장" },
      { name: "다진 돼지고기", amount: "150g" },
      { name: "배추 김치 또는 양배추", amount: "80g" },
      { name: "부추", amount: "30g" },
      { name: "간장", amount: "1큰술" },
      { name: "참기름", amount: "1작은술" },
      { name: "물", amount: "50ml (뚜껑 구이용)" },
    ],
    steps: [
      "배추(또는 양배추)를 잘게 다져 소금으로 절여 물기를 꼭 짭니다.",
      "다진 고기, 부추, 절인 야채에 간장, 참기름으로 버무려 소를 만듭니다.",
      "만두피에 소를 넣고 가장자리에 물을 발라 반달 모양으로 꼭 눌러 붙입니다.",
      "팬에 기름을 두르고 교자를 배열해 중불에서 바닥이 노릇해질 때까지 굽습니다.",
      "물 50ml를 붓고 뚜껑을 덮어 스팀으로 3~4분 익혀 완성합니다.",
    ],
    image: "/images/pancake.png",
    matchIngredients: ["만두피", "돼지고기", "양배추", "부추"],
  },
];

// Normalize and map synonyms for Korean food ingredients
const synonyms: { [key: string]: string[] } = {
  "파": ["대파", "파", "쪽파", "실파"],
  "대파": ["대파", "파", "쪽파", "실파"],
  "쪽파": ["대파", "파", "쪽파", "실파"],
  "돼지고기": ["돼지고기", "고기", "삼겹살", "목살", "앞다리살"],
  "소금": ["소금", "맛소금", "허브솔트"],
  "간장": ["간장", "진간장", "국간장", "양조간장"],
  "김치": ["김치", "신김치", "묵은지", "익은김치"],
  "깨": ["깨", "통깨", "참깨", "검은깨"],
  "마늘": ["마늘", "다진마늘", "다진 마늘", "통마늘"],
  "두부": ["두부", "찌개두부", "부침두부"],
  "오뎅": ["오뎅", "어묵"],
  "소고기": ["소고기", "쇠고기", "우육"],
  "닭고기": ["닭고기", "닭", "닭가슴살", "닭허벅지"],
  "면": ["파스타면", "스파게티면", "우동면", "소바면", "메밀면"],
};

function isMatch(userIng: string, targetIng: string): boolean {
  const u = userIng.trim().replace(/\s+/g, "");
  const t = targetIng.trim().replace(/\s+/g, "");

  if (u === t) return true;
  if (t.includes(u) || u.includes(t)) return true;

  for (const groupKey in synonyms) {
    const list = synonyms[groupKey];
    if (list.some((item) => u.includes(item) || item.includes(u))) {
      if (list.some((item) => t.includes(item) || item.includes(t))) {
        return true;
      }
    }
  }

  return false;
}

export interface MatchResult {
  recipe: Recipe;
  ownedIngredients: string[];
  missingIngredients: string[];
  matchRate: number;
}

export function getRecommendedRecipes(userIngredients: string[]): MatchResult[] {
  const results = RECIPES.map((recipe) => {
    const owned: string[] = [];
    const missing: string[] = [];

    recipe.matchIngredients.forEach((reqIng) => {
      const hasIt = userIngredients.some((userIng) => isMatch(userIng, reqIng));
      if (hasIt) {
        owned.push(reqIng);
      } else {
        missing.push(reqIng);
      }
    });

    const matchRate = Math.round((owned.length / recipe.matchIngredients.length) * 100);

    return {
      recipe,
      ownedIngredients: owned,
      missingIngredients: missing,
      matchRate,
    };
  });

  return results.sort((a, b) => {
    if (b.matchRate !== a.matchRate) {
      return b.matchRate - a.matchRate;
    }
    return a.missingIngredients.length - b.missingIngredients.length;
  });
}
